name: OptSpecClassifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - astropy=7.0.1
  - matplotlib=3.10.1
  - pandas=2.2.3
  - numpy=2.2.4
  - scipy=1.15.2
  - scikit-learn=1.6.1
  - joblib=1.4.2
  - notebook
